### PR TITLE
fix(dialog-renderer): check for transitions before awaiting transitonend

### LINKED ISSUE #190: "position" handler and no transitions issue
When "position" handler is being set and no transitions for dialog defined in css, the promise returned from DialogRenderer.showDialog() resolves on dialog CLOSE! transition end.

### PR DESCRIPTION
**Pull request by StrahilKazlachev**
fix #190

### CODE REVIEW

File: src/dialog-renderer.js [hunk 1]
```diff
@@ -25,6 +25,28 @@ let transitionEvent = (function() {
     }
   };
 }());
+let hasTransition = (function () {
+  const defaultDuration = '0s';
+  let transitionDuration;
+  let t;
+  let el = DOM.createElement('fakeelement');
+  let transitions = {
+    'transition': 'transitionDuration',
```
Comment (StrahilKazlachev) [inline src/dialog-renderer.js]: @PWKad I'm not entirely sure about prefixed names.

**Comment by PWKad** [comment]
@StrahilKazlachev this looks good to me, can you let me know if there is an order to merge in at?  As far as your question on `is this the best way to check for transitions in flight?` it seems so to me but perhaps @zewa666 could take a quick peek and see based on his previous work with multiple animation libraries if we need to account for any edge cases?

**Comment by StrahilKazlachev** [comment]
@PWKad no order for this one.
